=== Hello-Gitty/bloodmoon-asylum/kibuilder/src/main/java/groupe/e/kibuilder/data/Vocation.dtd
<!ELEMENT VOCATIONS (TYPE+)>
<!ELEMENT TYPE (VOCATION+)>
<!ELEMENT VOCATION (NOM,DESCRIPTION,PERKS+, TAGS?)>
<!ELEMENT PERKS (NOM,DESCRIPTION,ORDRE, TAGS?)>
<!ELEMENT ORDRE (NOM,DESCRIPTION, LEGALITE, JETS?, TAGS?)>
<!ELEMENT JETS (JET+)>
<!ELEMENT JET (COUT-PV?, COUT-ARGENT?, DESCRIPTION?, ((CARACTERISTIQUE, COMPETENCE, POTENTIEL, DIFFICULTE, CARACTERISTIQUE-OPOSEE?)|AUTOMATIQUE))>


<!ATTLIST TYPE name CDATA #REQUIRED>
<!ATTLIST PERKS niveau CDATA #REQUIRED>


<!ELEMENT NOM (#PCDATA)>
<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT CARACTERISTIQUE (#PCDATA)>
<!ELEMENT CARACTERISTIQUE-OPOSEE (#PCDATA)>
<!ELEMENT COMPETENCE (#PCDATA)>
<!ELEMENT COUT-PV (#PCDATA)>
<!ELEMENT COUT-ARGENT (#PCDATA)>
<!ELEMENT POTENTIEL (#PCDATA)>
<!ELEMENT DIFFICULTE (#PCDATA)>
<!ELEMENT AUTOMATIQUE (#PCDATA)>
<!ELEMENT LEGALITE (#PCDATA)>

<!ELEMENT TAGS (TAG+)>
<!ELEMENT TAG (#PCDATA)>

=== Hello-Gitty/bloodmoon-asylum/kibuilder/src/main/java/groupe/e/kibuilder/data/vocations.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VOCATIONS SYSTEM "Vocation.dtd" >
<VOCATIONS>
  <TYPE name="CARRIERE">
    <VOCATION>
      <NOM>NOM</NOM>
      <DESCRIPTION>DESCRIPTION</DESCRIPTION>
    </VOCATION>
  </TYPE>
  
    <TYPE name="TYPE">
    <VOCATION>
      <NOM>NOM</NOM>
      <DESCRIPTION>DESCRIPTION</DESCRIPTION>
    </VOCATION>
  </TYPE>
  
  
    <TYPE name="POLITIQUE">
    <VOCATION>
      <NOM>NOM</NOM>
      <DESCRIPTION>DESCRIPTION</DESCRIPTION>
    </VOCATION>
  </TYPE>
  
  
    <TYPE name="COMBAT">
    <VOCATION>
      <NOM>NOM</NOM>
      <DESCRIPTION>DESCRIPTION</DESCRIPTION>
    </VOCATION>
  </TYPE>
  
    <TYPE name="POUVOIR">
    <VOCATION>
      <NOM>NOM</NOM>
      <DESCRIPTION>DESCRIPTION</DESCRIPTION>
    </VOCATION>
  </TYPE>
  
  
</VOCATIONS>
